"""
DesktopAI v2.0 — Auto Organizer
File: src/domain/organizer/organizer.py

Executes organization plans with:

    - Safe file operations
    - Runtime conflict resolution
    - Batch tracking
    - Undo support
    - Database audit history
    - Memory learning
    - Detailed logging
    - Failure isolation
    - Windows-friendly filesystem handling

The organizer is intentionally defensive because filesystem operations
are inherently failure-prone.
"""

from __future__ import annotations

import shutil
import uuid
from pathlib import Path
from typing import Optional

from core.logger import get_logger

from domain.organizer.action import OrganizationAction
from domain.organizer.undo_stack import UndoStack

from infrastructure.config.settings import Settings
from infrastructure.storage.database import DB
from infrastructure.storage.memory_store import MemoryStore


logger = get_logger(__name__)


class AutoOrganizer:
    """
    Executes organization plans safely and maintains undo history.

    The organizer is responsible for execution.

    Planning belongs to OrganizationPlanner.

    Undo execution belongs to UndoStack.
    """

    def __init__(self) -> None:
        self.undo_stack = UndoStack()

        logger.debug(
            "Organizer: initialized"
        )

    # ==================================================================
    # PLAN EXECUTION
    # ==================================================================

    def execute_plan(
        self,
        actions: list[OrganizationAction],
        batch_id: Optional[str] = None,
    ) -> dict[str, int]:
        """
        Execute a list of organization actions.

        Parameters
        ----------
        actions:
            Organization actions generated by the planner.

        batch_id:
            Optional identifier used to group operations for undo.

        Returns
        -------
        dict[str, int]
            Execution statistics:

                {
                    "success": number of successful actions,
                    "failed": number of failed actions,
                    "skipped": number of skipped actions
                }
        """

        stats = {
            "success": 0,
            "failed": 0,
            "skipped": 0,
        }

        if not actions:
            logger.info(
                "Organizer: no actions to execute"
            )
            return stats

        if not batch_id:
            batch_id = str(uuid.uuid4())

        logger.info(
            "Organizer: executing plan — %d actions, batch_id=%s",
            len(actions),
            batch_id,
        )

        total = len(actions)

        for index, action in enumerate(actions, start=1):
            action_name = self._action_name(action)

            logger.debug(
                "Organizer: processing action %d/%d — %s",
                index,
                total,
                action_name,
            )

            try:
                self._execute_action(
                    action=action,
                    batch_id=batch_id,
                )

                if self._is_success(action):
                    stats["success"] += 1

                elif self._is_failed(action):
                    stats["failed"] += 1

                else:
                    stats["skipped"] += 1

            except Exception as exc:
                logger.error(
                    "Organizer: unexpected error executing %s: %s",
                    action_name,
                    exc,
                    exc_info=True,
                )

                self._mark_failed(
                    action,
                    str(exc),
                )

                stats["failed"] += 1

                self._record_failure(
                    action,
                    batch_id,
                )

        logger.info(
            "Organizer: plan complete — success=%d, failed=%d, skipped=%d",
            stats["success"],
            stats["failed"],
            stats["skipped"],
        )

        return stats

    # ==================================================================
    # SINGLE ACTION
    # ==================================================================

    def _execute_action(
        self,
        action: OrganizationAction,
        batch_id: str,
    ) -> None:
        """
        Execute one organization action.

        The destination is checked again immediately before execution.
        This protects against conflicts that appeared after planning.
        """

        source = self._source_path(action)

        planned_target = self._planned_target_path(action)

        if source is None:
            raise ValueError(
                "Organization action has no source_path"
            )

        if planned_target is None:
            raise ValueError(
                "Organization action has no planned_target_path"
            )

        if not source.exists():
            error_msg = (
                f"Source file no longer exists: {source}"
            )

            logger.warning(
                "Organizer: %s",
                error_msg,
            )

            self._mark_failed(
                action,
                error_msg,
            )

            self._record_failure(
                action,
                batch_id,
            )

            return

        # Resolve conflicts again at execution time.
        target = self._resolve_conflicts(
            source,
            planned_target,
        )

        self._set_actual_target(
            action,
            target,
        )

        action_type = self._action_type(action)

        logger.info(
            "Organizer: %s %s → %s",
            action_type.upper(),
            source.name,
            target,
        )

        try:
            # Ensure destination directory exists.
            target.parent.mkdir(
                parents=True,
                exist_ok=True,
            )

            # Execute actual filesystem operation.
            self._perform_file_operation(
                action,
                source,
                target,
            )

            # Verify that the operation really happened.
            if not self._operation_completed(
                action,
                source,
                target,
            ):
                raise OSError(
                    "Filesystem operation completed without "
                    "producing the expected result"
                )

            # ----------------------------------------------------------
            # Database audit history
            # ----------------------------------------------------------

            history_id = DB.record_history_entry(
                action_type=action_type,
                source_path=str(source),
                target_path=str(target),
                category=self._category(action),
                confidence=self._confidence(action),
                model=self._model_name(),
                status="completed",
                batch_id=batch_id,
            )

            # ----------------------------------------------------------
            # Mark action successful
            #
            # Do NOT assume OrganizationAction implements mark_success().
            # The current project action model exposes state differently.
            # ----------------------------------------------------------

            self._mark_success(
                action,
                target,
                history_id,
            )

            # ----------------------------------------------------------
            # CRITICAL:
            #
            # Store batch_id together with the action.
            #
            # This fixes the Milestone 7 failure where undo_batch()
            # previously returned 0.
            # ----------------------------------------------------------

            self.undo_stack.push(
                action,
                batch_id=batch_id,
            )

            logger.debug(
                "Organizer: undo stack updated — %s | batch=%s | batch_count=%d",
                self._action_name(action),
                batch_id,
                self.undo_stack.get_batch_count(batch_id),
            )

            # ----------------------------------------------------------
            # Learn high-confidence preferences
            # ----------------------------------------------------------

            self._learn_preference(
                action,
                target,
            )

        except PermissionError as exc:
            error_msg = (
                "File is locked, inaccessible, or permission was denied"
            )

            logger.warning(
                "Organizer: permission denied — %s: %s",
                self._action_name(action),
                exc,
            )

            self._mark_failed(
                action,
                error_msg,
            )

            self._record_failure(
                action,
                batch_id,
            )

        except FileNotFoundError as exc:
            error_msg = (
                "Source file no longer exists"
            )

            logger.warning(
                "Organizer: file disappeared during execution — %s",
                self._action_name(action),
            )

            self._mark_failed(
                action,
                error_msg,
            )

            self._record_failure(
                action,
                batch_id,
            )

        except OSError as exc:
            error_msg = str(exc)

            logger.error(
                "Organizer: filesystem failure for %s: %s",
                self._action_name(action),
                exc,
                exc_info=True,
            )

            self._mark_failed(
                action,
                error_msg,
            )

            self._record_failure(
                action,
                batch_id,
            )

        except Exception as exc:
            error_msg = str(exc)

            logger.error(
                "Organizer: failed to execute %s: %s",
                self._action_name(action),
                exc,
                exc_info=True,
            )

            self._mark_failed(
                action,
                error_msg,
            )

            self._record_failure(
                action,
                batch_id,
            )

    # ==================================================================
    # CONFLICT RESOLUTION
    # ==================================================================

    def _resolve_conflicts(
        self,
        source: Path,
        target: Path,
    ) -> Path:
        """
        Resolve a destination filename conflict.

        Example:

            invoice.pdf
            invoice_1.pdf
            invoice_2.pdf

        The original source filename is preserved as the naming base.
        """

        if not target.exists():
            return target

        stem = source.stem
        suffix = source.suffix

        counter = 1

        while True:
            candidate = (
                target.parent
                / f"{stem}_{counter}{suffix}"
            )

            if not candidate.exists():
                logger.info(
                    "Organizer: runtime conflict resolved — %s → %s",
                    target.name,
                    candidate.name,
                )

                return candidate

            counter += 1

    # ==================================================================
    # FILE OPERATIONS
    # ==================================================================

    def _perform_file_operation(
        self,
        action: OrganizationAction,
        source: Path,
        target: Path,
    ) -> None:
        """
        Perform the actual filesystem operation.
        """

        action_type = self._action_type(action)

        if action_type == "move":
            shutil.move(
                str(source),
                str(target),
            )
            return

        if action_type == "copy":
            shutil.copy2(
                str(source),
                str(target),
            )
            return

        if action_type == "rename":
            source.rename(target)
            return

        raise ValueError(
            f"Unknown action type: {action_type}"
        )

    def _operation_completed(
        self,
        action: OrganizationAction,
        source: Path,
        target: Path,
    ) -> bool:
        """
        Verify that the requested filesystem operation completed.
        """

        action_type = self._action_type(action)

        if action_type == "move":
            return (
                target.exists()
                and not source.exists()
            )

        if action_type == "copy":
            return target.exists()

        if action_type == "rename":
            return (
                target.exists()
                and not source.exists()
            )

        return False

    # ==================================================================
    # UNDO
    # ==================================================================

    def undo_last_batch(
        self,
        batch_id: str,
    ) -> int:
        """
        Undo all successfully executed actions in a batch.

        Returns the number of successfully reversed actions.
        """

        if not batch_id:
            logger.warning(
                "Organizer: cannot undo empty batch ID"
            )
            return 0

        logger.info(
            "Organizer: initiating undo for batch %s",
            batch_id,
        )

        available = self.undo_stack.get_batch_count(
            batch_id
        )

        logger.debug(
            "Organizer: batch %s has %d undoable action(s)",
            batch_id,
            available,
        )

        reversed_count = self.undo_stack.undo_batch(
            batch_id
        )

        logger.info(
            "Organizer: undo complete — %d actions reversed",
            reversed_count,
        )

        return reversed_count

    def undo_last_action(self) -> bool:
        """
        Undo the most recently executed successful action.
        """

        logger.info(
            "Organizer: undoing last action"
        )

        return self.undo_stack.undo_last_action()

    # ==================================================================
    # DATABASE FAILURE LOGGING
    # ==================================================================

    def _record_failure(
        self,
        action: OrganizationAction,
        batch_id: str,
    ) -> None:
        """
        Record a failed operation in the audit database.

        Database failures are isolated from the organizer so that a
        database issue does not hide the original filesystem failure.
        """

        try:
            DB.record_history_entry(
                action_type=self._action_type(action),
                source_path=str(
                    self._source_path(action)
                    or ""
                ),
                target_path=str(
                    self._planned_target_path(action)
                    or ""
                ),
                category=self._category(action),
                confidence=self._confidence(action),
                model=self._model_name(),
                status="failed",
                error_message=self._error_message(action),
                batch_id=batch_id,
            )

        except Exception as exc:
            logger.error(
                "Organizer: could not record failure in database: %s",
                exc,
                exc_info=True,
            )

    # ==================================================================
    # MEMORY LEARNING
    # ==================================================================

    def _learn_preference(
        self,
        action: OrganizationAction,
        target: Path,
    ) -> None:
        """
        Store a folder preference for high-confidence actions.
        """

        confidence = self._confidence(action)

        if confidence < 0.90:
            return

        source = self._source_path(action)

        if source is None:
            return

        extension = source.suffix.lower()

        if not extension:
            return

        try:
            MemoryStore.remember_folder(
                filename_or_extension=extension,
                folder_path=str(target.parent),
                confidence=confidence,
            )

            logger.debug(
                "Organizer: learned preference — %s → %s",
                extension,
                target.parent,
            )

        except Exception as exc:
            # Learning failure must NEVER invalidate a successful file
            # operation.
            logger.warning(
                "Organizer: unable to save memory preference for %s: %s",
                source.name,
                exc,
            )

    # ==================================================================
    # ACTION STATE HELPERS
    # ==================================================================

    @staticmethod
    def _is_success(
        action: OrganizationAction,
    ) -> bool:
        """
        Determine whether an action succeeded.

        Supports the current OrganizationAction implementation without
        requiring mark_success().
        """

        value = getattr(
            action,
            "is_success",
            False,
        )

        if callable(value):
            try:
                return bool(value())
            except Exception:
                return False

        return bool(value)

    @staticmethod
    def _is_failed(
        action: OrganizationAction,
    ) -> bool:
        """
        Determine whether an action failed.
        """

        value = getattr(
            action,
            "is_failed",
            False,
        )

        if callable(value):
            try:
                return bool(value())
            except Exception:
                return False

        return bool(value)

    @staticmethod
    def _mark_success(
        action: OrganizationAction,
        target: Path,
        history_id: object,
    ) -> None:
        """
        Mark an action successful.

        Compatible with multiple OrganizationAction implementations.
        """

        # Newer implementation may provide mark_success().
        mark_success = getattr(
            action,
            "mark_success",
            None,
        )

        if callable(mark_success):
            try:
                mark_success(
                    target,
                    history_id,
                )
                return
            except TypeError:
                try:
                    mark_success(target)
                    return
                except Exception:
                    pass

        # Existing implementation usually exposes direct fields.
        for attribute, value in (
            ("actual_target_path", target),
            ("history_id", history_id),
            ("status", "completed"),
            ("state", "completed"),
        ):
            try:
                setattr(
                    action,
                    attribute,
                    value,
                )
            except Exception:
                pass

    @staticmethod
    def _mark_failed(
        action: OrganizationAction,
        error_message: str,
    ) -> None:
        """
        Mark an action failed.

        Compatible with multiple OrganizationAction implementations.
        """

        mark_failed = getattr(
            action,
            "mark_failed",
            None,
        )

        if callable(mark_failed):
            try:
                mark_failed(error_message)
                return
            except Exception:
                pass

        for attribute, value in (
            ("status", "failed"),
            ("state", "failed"),
            ("error_message", error_message),
        ):
            try:
                setattr(
                    action,
                    attribute,
                    value,
                )
            except Exception:
                pass

    # ==================================================================
    # ACTION DATA HELPERS
    # ==================================================================

    @staticmethod
    def _source_path(
        action: OrganizationAction,
    ) -> Optional[Path]:
        value = getattr(
            action,
            "source_path",
            None,
        )

        if value is None:
            return None

        return Path(value)

    @staticmethod
    def _planned_target_path(
        action: OrganizationAction,
    ) -> Optional[Path]:
        value = getattr(
            action,
            "planned_target_path",
            None,
        )

        if value is None:
            return None

        return Path(value)

    @staticmethod
    def _set_actual_target(
        action: OrganizationAction,
        target: Path,
    ) -> None:
        """
        Store the runtime target path.

        If OrganizationAction supports actual_target_path, use it.
        """

        try:
            setattr(
                action,
                "actual_target_path",
                target,
            )
        except Exception:
            pass

    @staticmethod
    def _action_type(
        action: OrganizationAction,
    ) -> str:
        return str(
            getattr(
                action,
                "action_type",
                "",
            )
        ).strip().lower()

    @staticmethod
    def _category(
        action: OrganizationAction,
    ) -> str:
        return str(
            getattr(
                action,
                "category",
                "",
            )
        )

    @staticmethod
    def _confidence(
        action: OrganizationAction,
    ) -> float:
        try:
            return float(
                getattr(
                    action,
                    "confidence",
                    0.0,
                )
            )
        except (TypeError, ValueError):
            return 0.0

    @staticmethod
    def _error_message(
        action: OrganizationAction,
    ) -> Optional[str]:
        value = getattr(
            action,
            "error_message",
            None,
        )

        if value is None:
            return None

        return str(value)

    @staticmethod
    def _action_name(
        action: OrganizationAction,
    ) -> str:
        """
        Get filename safely.

        This intentionally does NOT use action.source_filename because
        that property does not exist in the current OrganizationAction.
        """

        source = getattr(
            action,
            "source_path",
            None,
        )

        if source is not None:
            try:
                return Path(source).name
            except Exception:
                pass

        filename = getattr(
            action,
            "filename",
            None,
        )

        if filename:
            return str(filename)

        return "<unknown file>"

    @staticmethod
    def _model_name() -> str:
        """
        Safely retrieve the configured AI model.
        """

        try:
            return str(
                Settings.ai.model
            )
        except Exception:
            return "unknown"